<a href="https://www.kaggle.com/code/omborse771924/nasa-power-climate-risk-extremes?scriptVersionId=323999900" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/kanchana1990/nasa-power-climate-risk-and-extremes/nasa_power_climate_risk_indices_190_capitals_1990_2024.csv

## Loading Dataset

In [2]:
df=pd.read_csv('/kaggle/input/datasets/kanchana1990/nasa-power-climate-risk-and-extremes/nasa_power_climate_risk_indices_190_capitals_1990_2024.csv')

In [3]:
df.head()

,city,iso_alpha3,latitude,longitude,continent,who_region,wb_income_group,year,data_days,temp_mean_c,...,solar_clearness_idx,solar_peak_days,solar_annual_kwh_m2,pressure_mean_kpa,pressure_std_kpa,climate_volatility,gdp_per_capita_usd,population,urban_pop_pct,energy_use_kg_oil_eq
0,Abu Dhabi,ARE,24.47,54.37,E.Mediterranean,EMR,High,1990,365.0,27.695068,...,NaN,0.0,579.30,100.775370,0.801732,0.1810,26709.993440,1898220.0,78.685768,10740.842922
1,Abu Dhabi,ARE,24.47,54.37,E.Mediterranean,EMR,High,1991,365.0,27.084274,...,NaN,0.0,556.38,100.800055,0.766893,0.0809,25690.968632,2006626.0,78.553863,11690.097020
2,Abu Dhabi,ARE,24.47,54.37,E.Mediterranean,EMR,High,1992,366.0,26.680383,...,NaN,0.0,546.73,100.900656,0.778965,0.3512,25648.272776,2114730.0,78.441374,10562.899438
3,Abu Dhabi,ARE,24.47,54.37,E.Mediterranean,EMR,High,1993,365.0,27.617425,...,NaN,0.0,571.01,100.864959,0.770028,0.5771,25032.782270,2222093.0,78.351924,10572.669831
4,Abu Dhabi,ARE,24.47,54.37,E.Mediterranean,EMR,High,1994,365.0,27.643479,...,NaN,0.0,565.40,100.801123,0.834037,0.0204,25472.639658,2328188.0,78.289134,11178.398481

In [4]:
df.tail()

,city,iso_alpha3,latitude,longitude,continent,who_region,wb_income_group,year,data_days,temp_mean_c,...,solar_clearness_idx,solar_peak_days,solar_annual_kwh_m2,pressure_mean_kpa,pressure_std_kpa,climate_volatility,gdp_per_capita_usd,population,urban_pop_pct,energy_use_kg_oil_eq
6645,Zagreb,HRV,45.81,15.98,Europe,EUR,High,2020,366.0,11.571475,...,0.495301,0.0,386.43,99.425546,0.778245,3.3412,14807.560854,3914206.0,56.528486,2104.845306
6646,Zagreb,HRV,45.81,15.98,Europe,EUR,High,2021,365.0,11.235315,...,0.485151,0.0,383.06,99.355425,0.734905,3.3534,17788.786582,3878981.0,56.768350,2212.497211
6647,Zagreb,HRV,45.81,15.98,Europe,EUR,High,2022,365.0,12.277863,...,0.491671,0.0,386.18,99.477644,0.744171,3.4615,18465.541442,3855641.0,56.997757,2154.954833
6648,Zagreb,HRV,45.81,15.98,Europe,EUR,High,2023,365.0,12.368575,...,0.470164,0.0,363.65,99.254712,0.789971,4.0202,22184.227930,3859686.0,57.243156,2237.233699
6649,Zagreb,HRV,45.81,15.98,Europe,EUR,High,2024,366.0,13.187842,...,0.477541,0.0,369.97,99.320984,0.789348,3.3885,24050.439793,3866200.0,57.515898,NaN

In [5]:
df.describe()

,latitude,longitude,year,data_days,temp_mean_c,temp_max_c,temp_min_c,temp_std_c,temp_range_mean_c,temp_seasonal_amp,...,solar_clearness_idx,solar_peak_days,solar_annual_kwh_m2,pressure_mean_kpa,pressure_std_kpa,climate_volatility,gdp_per_capita_usd,population,urban_pop_pct,energy_use_kg_oil_eq
count,6650.000000,6650.000000,6650.000000,6650.000000,6650.000000,6650.000000,6650.000000,6650.000000,6650.000000,6650.000000,...,4560.000000,6650.0,6650.000000,6650.000000,6650.000000,6650.000000,6465.000000,6.580000e+03,6580.000000,5050.000000
mean,18.572421,22.186158,2007.000000,367.179549,19.676911,34.612319,5.021768,4.662159,8.022112,12.745047,...,0.536499,0.0,489.724138,96.442585,0.435515,1.565950,10944.947814,3.555906e+07,54.797910,2274.443035
std,24.232271,66.202217,10.100264,26.434372,7.560244,5.565391,15.394534,3.517533,4.264271,9.775679,...,0.074366,0.0,108.850770,6.426781,0.303449,2.198223,18783.848991,1.330653e+08,23.016545,2757.956448
min,-41.290000,-175.200000,1990.000000,365.000000,-3.075355,15.550000,-45.040000,0.346657,0.546858,0.330968,...,0.365726,0.0,213.390000,67.358388,0.069549,0.003300,22.952133,8.798000e+03,5.274941,0.000000
25%,3.870000,-6.830000,1998.000000,365.000000,13.222832,30.400000,-6.567500,1.311086,4.622017,3.548487,...,0.481500,0.0,423.240000,93.720856,0.163692,0.248825,1014.402797,1.956066e+06,35.424115,496.586814
50%,15.450000,21.090000,2007.000000,365.000000,21.572223,34.100000,7.585000,3.784264,8.589868,10.363357,...,0.543712,0.0,507.275000,99.460219,0.350805,0.655950,3435.288047,7.381301e+06,55.623062,1249.437479
75%,39.920000,49.870000,2016.000000,366.000000,26.564868,38.587500,18.607500,7.737957,11.133192,21.206752,...,0.594252,0.0,563.645000,100.849740,0.656594,2.032200,11501.226519,2.312902e+07,73.249034,2893.639612
max,64.140000,179.200000,2024.000000,732.000000,30.141311,52.640000,26.950000,17.462571,17.059126,46.194194,...,0.706384,0.0,1185.660000,101.945863,1.684677,30.616700,206780.590353,1.450936e+09,100.000000,21557.475076

In [6]:
df.isnull()

,city,iso_alpha3,latitude,longitude,continent,who_region,wb_income_group,year,data_days,temp_mean_c,...,solar_clearness_idx,solar_peak_days,solar_annual_kwh_m2,pressure_mean_kpa,pressure_std_kpa,climate_volatility,gdp_per_capita_usd,population,urban_pop_pct,energy_use_kg_oil_eq
0,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6645,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6646,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6647,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6648,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
6649,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True

In [7]:
df.isnull().sum()

city                       0
iso_alpha3                 0
latitude                   0
longitude                  0
continent                  0
who_region                 0
wb_income_group            0
year                       0
data_days                  0
temp_mean_c                0
temp_max_c                 0
temp_min_c                 0
temp_std_c                 0
temp_range_mean_c          0
temp_seasonal_amp          0
temp_yoy_change          190
temp_5yr_mean            380
temp_anomaly             380
days_above_35c             0
days_above_40c             0
days_below_0c              0
days_below_minus10c        0
heat_stress_index          0
cold_stress_index          0
drought_stress_days        0
ideal_climate_days         0
precip_total_mm            0
precip_mean_mm             0
precip_max_day_mm          0
precip_std_mm              0
precip_yoy_change        190
days_heavy_rain            0
days_moderate_rain         0
days_dry                   0
rh_mean_pct                0
rh_max_pct                 0
dewpoint_mean_c            0
humidity_stress_days       0
wind_mean_ms               0
wind_max_ms                0
wind_std_ms                0
high_wind_days             0
wind_power_density         0
solar_total_mj             0
solar_mean_mj              0
solar_clear_mean_mj        0
solar_clearness_idx     2090
solar_peak_days            0
solar_annual_kwh_m2        0
pressure_mean_kpa          0
pressure_std_kpa           0
climate_volatility         0
gdp_per_capita_usd       185
population                70
urban_pop_pct             70
energy_use_kg_oil_eq    1600
dtype: int64

In [8]:
missing_cols = [

    'temp_yoy_change',
    'temp_5yr_mean',
    'temp_anomaly',
    'precip_yoy_change',
    'solar_clearness_idx',
    'gdp_per_capita_usd',
    'population',
    'urban_pop_pct',
    'energy_use_kg_oil_eq'

]


for col in missing_cols:

    df[col] = df[col].fillna(
        df[col].median()
    )

In [9]:
df.isnull().sum()

city                    0
iso_alpha3              0
latitude                0
longitude               0
continent               0
who_region              0
wb_income_group         0
year                    0
data_days               0
temp_mean_c             0
temp_max_c              0
temp_min_c              0
temp_std_c              0
temp_range_mean_c       0
temp_seasonal_amp       0
temp_yoy_change         0
temp_5yr_mean           0
temp_anomaly            0
days_above_35c          0
days_above_40c          0
days_below_0c           0
days_below_minus10c     0
heat_stress_index       0
cold_stress_index       0
drought_stress_days     0
ideal_climate_days      0
precip_total_mm         0
precip_mean_mm          0
precip_max_day_mm       0
precip_std_mm           0
precip_yoy_change       0
days_heavy_rain         0
days_moderate_rain      0
days_dry                0
rh_mean_pct             0
rh_max_pct              0
dewpoint_mean_c         0
humidity_stress_days    0
wind_mean_ms            0
wind_max_ms             0
wind_std_ms             0
high_wind_days          0
wind_power_density      0
solar_total_mj          0
solar_mean_mj           0
solar_clear_mean_mj     0
solar_clearness_idx     0
solar_peak_days         0
solar_annual_kwh_m2     0
pressure_mean_kpa       0
pressure_std_kpa        0
climate_volatility      0
gdp_per_capita_usd      0
population              0
urban_pop_pct           0
energy_use_kg_oil_eq    0
dtype: int64

In [10]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
6645    False
6646    False
6647    False
6648    False
6649    False
Length: 6650, dtype: bool

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.columns

Index(['city', 'iso_alpha3', 'latitude', 'longitude', 'continent',
       'who_region', 'wb_income_group', 'year', 'data_days', 'temp_mean_c',
       'temp_max_c', 'temp_min_c', 'temp_std_c', 'temp_range_mean_c',
       'temp_seasonal_amp', 'temp_yoy_change', 'temp_5yr_mean', 'temp_anomaly',
       'days_above_35c', 'days_above_40c', 'days_below_0c',
       'days_below_minus10c', 'heat_stress_index', 'cold_stress_index',
       'drought_stress_days', 'ideal_climate_days', 'precip_total_mm',
       'precip_mean_mm', 'precip_max_day_mm', 'precip_std_mm',
       'precip_yoy_change', 'days_heavy_rain', 'days_moderate_rain',
       'days_dry', 'rh_mean_pct', 'rh_max_pct', 'dewpoint_mean_c',
       'humidity_stress_days', 'wind_mean_ms', 'wind_max_ms', 'wind_std_ms',
       'high_wind_days', 'wind_power_density', 'solar_total_mj',
       'solar_mean_mj', 'solar_clear_mean_mj', 'solar_clearness_idx',
       'solar_peak_days', 'solar_annual_kwh_m2', 'pressure_mean_kpa',
       'pressure_std_kpa', 'climate_volatility', 'gdp_per_capita_usd',
       'population', 'urban_pop_pct', 'energy_use_kg_oil_eq'],
      dtype='object')

## EDA